name: torchenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.0.5
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - cryptography=41.0.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytorch=2.1.2
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5